### PR TITLE
updates tested up to 5.7 (current WP release)

### PR DESCRIPTION
**Pull request by simpixelated**
https://app.clubhouse.io/ghostinspector/story/4408/test-wordpress-plugin-on-wpv5-7

### CODE REVIEW

**Comment by simpixelated** [comment]
@justinklemm it seems like this is an issue with the `wordpress:cli` docker image and not related to the plugin at all:
https://github.com/docker-library/wordpress/issues/594

Any problem with me making these changes in svn (which is what actually updates the plugin directory). Since it's just an update to the readme and the assets (for the logos) it's not really a code change that requires a new release/tag by WordPress plugin standards.

**Review by justinklemm — DISMISSED** [review]
Cool w/me

**Comment by justinklemm** [comment]
I can merge it when you're ready (even if the check is failing)

**Comment by simpixelated** [comment]
It doesn't really need to be merged. Let's leave it open while I troubleshoot docker, but I'll make the changes in svn now

**Comment by simpixelated** [comment]
also fixes https://app.clubhouse.io/ghostinspector/story/4708/fix-wp-cli-install-error

**Review by justinklemm — APPROVED** [review]
Nice! Is the logo managed from the plugin's profile?

**Comment by simpixelated** [comment]
@justinklemm it's in a separate folder in svn called `assets`. Do you think it should live in this git repo too?

**Comment by justinklemm** [comment]
@simpixelated Yea, we should probably keep anything that's in the SVN repo in here also.

**Pull request merged**
